sudo: required
dist: xenial
language: c

# test with both compilers
compiler:
  - clang
  - gcc

  # remove older version of CMake, install latest version with pip
install:
  - sudo apt update
  - sudo apt install -y build-essential libgmp-dev libsodium-dev
  - sudo rm -rf /usr/local/cmake*
  - sudo -H pip install cmake

script:
  - cd external/amcl
  - sudo ./setup_amcl.sh
  - cd ../..
  - cmake .
  - make
  - make test
